# Langdon Hatton
## ds-160
## numpy assignment

In [1]:
import numpy as np

In [6]:
array1=np.arange(10,41,10)

In [16]:
array1.resize(2,2)

In [17]:
array1**2

array([[ 100,  400],
       [ 900, 1600]])

In [18]:
array1+100

array([[110, 120],
       [130, 140]])

In [19]:
array1*5

array([[ 50, 100],
       [150, 200]])

In [20]:
np.sqrt(array1)

array([[3.16227766, 4.47213595],
       [5.47722558, 6.32455532]])

In [21]:
array2=np.arange(3,28, 3)

In [23]:
array2.resize(3,3)

In [24]:
array2

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [40]:
array3=np.linspace(10,20,9)

In [41]:
array3

array([10.  , 11.25, 12.5 , 13.75, 15.  , 16.25, 17.5 , 18.75, 20.  ])

In [42]:
array3.resize(3,3)

In [43]:
array2*array3

array([[ 30. ,  67.5, 112.5],
       [165. , 225. , 292.5],
       [367.5, 450. , 540. ]])

In [53]:
pro1=np.load('process1.npy')

In [54]:
pro1

array([[52, 12, 81,  0, 58]], dtype=int32)

In [55]:
pro2=np.load('process2.npy')

In [56]:
pro3=np.load('process3.npy')

In [57]:
pro4=np.load('process4.npy')

In [58]:
pro5=np.load('process5.npy')

In [61]:
process=np.vstack((pro1,pro2,pro3,pro4,pro5))

In [62]:
process

array([[52, 12, 81,  0, 58],
       [96,  4, 61, 16, 43],
       [38, 96, 45, 17, 58],
       [97, 21, 22, 25,  6],
       [77,  6, 19,  2, 74]], dtype=int32)

In [66]:
col1=process[:,:1]

In [68]:
col1.mean()

72.0

In [80]:
col2=process[:,1:2]

In [81]:
col2

array([[12],
       [ 4],
       [96],
       [21],
       [ 6]], dtype=int32)

In [82]:
col2.mean()

27.8

In [83]:
col3=process[:,2:3]

In [88]:
col3

array([[81],
       [61],
       [45],
       [22],
       [19]], dtype=int32)

In [84]:
col3.mean()

45.6

In [85]:
col4=process[:,3:4]

In [86]:
col4

array([[ 0],
       [16],
       [17],
       [25],
       [ 2]], dtype=int32)

In [87]:
col4.mean()

12.0

In [89]:
col5=process[:,4:5]

In [90]:
col5

array([[58],
       [43],
       [58],
       [ 6],
       [74]], dtype=int32)

In [91]:
col5.mean()

47.8